# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Learning Notes
author: Felix Trier
logo: images/icon_transparent.png
copyright: '2024'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 100

latex:
  latex_documents:
    targetname: learning-notes.tex

launch_buttons:
  binderhub_url: "https://mybinder.org"

repository:
  url: https://github.com/ftrier/learning-notes  # Online location of your book
  path_to_book: learning-notes  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <a href='https://ftrier-github-io.translate.goog/learning-notes/intro.html?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=de&_x_tr_pto=wapp'>German🇩🇪 Version</a>

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid